In [1]:
import MDAnalysis as mda

In [2]:
u=mda.Universe("final_nanodisc_bilayer_310K_final_clean_min.gro")

In [3]:
chain1_N1_N3 = u.select_atoms("((resname DA DG and name N1) or (resname DT DC and name N3) or (resname TO3 TO5 and name N3)) and (resid 1:413)")
chain2_N1_N3 = u.select_atoms("((resname DA DG and name N1) or (resname DT DC and name N3)) and (resid 414:560)")
print(f"{len(chain1_N1_N3)}, {len(chain2_N1_N3)}")

147, 147

In [4]:
import pandas as pd

# Convert chain2_N1_N3 to a DataFrame
chain2_N1_N3_df = pd.DataFrame({
    'Atom ID': chain2_N1_N3.ids,
    'Atom Name': chain2_N1_N3.names,
    'Residue Name': chain2_N1_N3.resnames,
    'Residue ID': chain2_N1_N3.resids,
    'Segment ID': chain2_N1_N3.segids,
    'Position': list(chain2_N1_N3.positions)
})

print(chain2_N1_N3_df)

     Atom ID Atom Name Residue Name  Residue ID Segment ID  \
0       9440        N1           DA         414     SYSTEM
1       9474        N1           DG         415     SYSTEM
2       9505        N3           DT         416     SYSTEM
3       9539        N1           DG         417     SYSTEM
4       9570        N3           DT         418     SYSTEM
..       ...       ...          ...         ...        ...
142    14026        N1           DA         556     SYSTEM
143    14058        N1           DA         557     SYSTEM
144    14090        N1           DA         558     SYSTEM
145    14122        N1           DA         559     SYSTEM
146    14154        N1           DA         560     SYSTEM

                              Position
0          [74.57, 177.43, 104.090004]
1    [78.060005, 177.70999, 103.57001]
2        [81.5, 178.26999, 103.950005]
3              [84.91, 179.82, 102.63]
4           [88.12, 179.27, 100.71999]
..                                 ...
142        [57.82, 169.97, 100.880005]
143     [60.079998, 172.49, 101.56999]
144        [62.93, 174.18, 102.770004]
145        [66.14, 175.27, 103.590004]
146            [69.67, 176.22, 103.74]

[147 rows x 6 columns]

In [5]:

# Convert chain2_N1_N3 to a DataFrame
chain1_N1_N3_df = pd.DataFrame({
    'Atom ID': chain1_N1_N3.ids,
    'Atom Name': chain1_N1_N3.names,
    'Residue Name': chain1_N1_N3.resnames,
    'Residue ID': chain1_N1_N3.resids,
    'Segment ID': chain1_N1_N3.segids,
    'Position': list(chain1_N1_N3.positions)
})

print(chain1_N1_N3_df)

     Atom ID Atom Name Residue Name  Residue ID Segment ID  \
0         18        N3          TO5           1     SYSTEM
1        398        N3           DT          21     SYSTEM
2        430        N3           DT          22     SYSTEM
3        462        N3           DT          23     SYSTEM
4        494        N3           DT          24     SYSTEM
..       ...       ...          ...         ...        ...
142     8946        N1           DA         390     SYSTEM
143     8980        N3           DC         391     SYSTEM
144     9008        N1           DA         392     SYSTEM
145     9042        N3           DC         393     SYSTEM
146     9070        N3          TO3         394     SYSTEM

                              Position
0              [70.42, 173.02, 102.71]
1           [67.15, 173.04001, 105.26]
2       [63.559998, 172.98001, 105.54]
3           [59.99, 172.73001, 104.74]
4              [56.77, 171.64, 103.34]
..                                 ...
142            [87.02, 182.05, 100.09]
143         [82.869995, 182.33, 99.31]
144        [81.020004, 178.58, 100.17]
145  [77.340004, 177.59001, 99.630005]
146      [75.02, 174.66998, 101.96999]

[147 rows x 6 columns]

In [6]:
# Reverse chain2_N1_N3_df based on its index
chain2_N1_N3_df_reversed = chain2_N1_N3_df.iloc[::-1].reset_index(drop=True)

print(chain2_N1_N3_df_reversed)

     Atom ID Atom Name Residue Name  Residue ID Segment ID  \
0      14154        N1           DA         560     SYSTEM
1      14122        N1           DA         559     SYSTEM
2      14090        N1           DA         558     SYSTEM
3      14058        N1           DA         557     SYSTEM
4      14026        N1           DA         556     SYSTEM
..       ...       ...          ...         ...        ...
142     9570        N3           DT         418     SYSTEM
143     9539        N1           DG         417     SYSTEM
144     9505        N3           DT         416     SYSTEM
145     9474        N1           DG         415     SYSTEM
146     9440        N1           DA         414     SYSTEM

                              Position
0              [69.67, 176.22, 103.74]
1          [66.14, 175.27, 103.590004]
2          [62.93, 174.18, 102.770004]
3       [60.079998, 172.49, 101.56999]
4          [57.82, 169.97, 100.880005]
..                                 ...
142         [88.12, 179.27, 100.71999]
143            [84.91, 179.82, 102.63]
144      [81.5, 178.26999, 103.950005]
145  [78.060005, 177.70999, 103.57001]
146        [74.57, 177.43, 104.090004]

[147 rows x 6 columns]

In [7]:
merged_df = pd.DataFrame({
    'Atom ID (chain1)': chain1_N1_N3_df['Atom ID'],
    'Atom ID (chain2)': chain2_N1_N3_df_reversed['Atom ID'],
    'Residue Name (chain1)': chain1_N1_N3_df['Residue Name'],
    
    'Residue Name (chain2)': chain2_N1_N3_df_reversed['Residue Name'],
    'Residue ID (chain1)': chain1_N1_N3_df['Residue ID'],
    'Residue ID (chain2)': chain2_N1_N3_df_reversed['Residue ID']
   
})
#print(merged_df)
merged_df.to_csv('merged_df.csv', index=False)
merged_df

,Atom ID (chain1),Atom ID (chain2),Residue Name (chain1),Residue Name (chain2),Residue ID (chain1),Residue ID (chain2)
0,18,14154,TO5,DA,1,560
1,398,14122,DT,DA,21,559
2,430,14090,DT,DA,22,558
3,462,14058,DT,DA,23,557
4,494,14026,DT,DA,24,556
...,...,...,...,...,...,...
142,8946,9570,DA,DT,390,418
143,8980,9539,DC,DG,391,417
144,9008,9505,DA,DT,392,416
145,9042,9474,DC,DG,393,415
146,9070,9440,TO3,DA,394,414

In [10]:
# Add new columns with default values
merged_df['atom_i'] = merged_df['Atom ID (chain1)']
merged_df['atom_j'] = merged_df['Atom ID (chain2)']
merged_df['func'] = 10  
merged_df['r0'] = 0.298  
merged_df['r1'] = 0.299  #
merged_df['r2'] = 0.300 # 
merged_df['k(kJ mol^-1 nm^-2)'] = 10000  # Example default value
merged_df[";"] = ";"  # Adding a column with a semicolon as its value
merged_df['Atom ID (chain1)'] = chain1_N1_N3_df['Atom ID']
merged_df['Atom ID (chain2)'] = chain2_N1_N3_df_reversed['Atom ID']
merged_df['Residue Name (chain1)'] = chain1_N1_N3_df['Residue Name']
merged_df['Residue Name (chain2)'] = chain2_N1_N3_df_reversed['Residue Name']
merged_df['Residue ID (chain1)'] = chain1_N1_N3_df['Residue ID']
merged_df['Residue ID (chain2)'] = chain2_N1_N3_df_reversed['Residue ID']
# Create a new DataFrame with selected columns from merged_df
new_df = merged_df[['atom_i', 'atom_j', 'func', 'r0', 'r1', 'r2', 'k(kJ mol^-1 nm^-2)',";",'Atom ID (chain1)','Atom ID (chain2)','Residue Name (chain1)','Residue Name (chain2)','Residue ID (chain1)','Residue ID (chain2)' ]]

new_df

,atom_i,atom_j,func,r0,r1,r2,k(kJ mol^-1 nm^-2),;,Atom ID (chain1),Atom ID (chain2),Residue Name (chain1),Residue Name (chain2),Residue ID (chain1),Residue ID (chain2)
0,18,14154,10,0.298,0.299,0.3,10000,;,18,14154,TO5,DA,1,560
1,398,14122,10,0.298,0.299,0.3,10000,;,398,14122,DT,DA,21,559
2,430,14090,10,0.298,0.299,0.3,10000,;,430,14090,DT,DA,22,558
3,462,14058,10,0.298,0.299,0.3,10000,;,462,14058,DT,DA,23,557
4,494,14026,10,0.298,0.299,0.3,10000,;,494,14026,DT,DA,24,556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,8946,9570,10,0.298,0.299,0.3,10000,;,8946,9570,DA,DT,390,418
143,8980,9539,10,0.298,0.299,0.3,10000,;,8980,9539,DC,DG,391,417
144,9008,9505,10,0.298,0.299,0.3,10000,;,9008,9505,DA,DT,392,416
145,9042,9474,10,0.298,0.299,0.3,10000,;,9042,9474,DC,DG,393,415
146,9070,9440,10,0.298,0.299,0.3,10000,;,9070,9440,TO3,DA,394,414

In [11]:
# Open the topology file in append mode
with open('create_topology_file_bond_neg.itp', 'a') as topo_file:
    # Write the [ bonds ] section header
    topo_file.write('\n[ bonds ]\n')
    
    # Iterate through new_df and write each row in the desired format
    for _, row in new_df.iterrows():
        topo_file.write(f"{row['atom_i']:>5} {row['atom_j']:>5} {row['func']:>5} {row['r0']:>5} {row['r1']:>8.3f} {row['r2']:>8.3f} {row['k(kJ mol^-1 nm^-2)']:>8} {row[';']} {row['Residue Name (chain1)']} {row['Residue Name (chain2)']} {row['Residue ID (chain1)']} {row['Residue ID (chain2)']}\n")